function convertSQL() {
  let sql = document.getElementById("oracleInput").value;

  if (!sql.trim()) {
    alert("Please enter Oracle SQL code.");
    return;
  }

  let converted = sql;

  // Data types
  converted = converted.replace(/\bVARCHAR2\s*\(([^)]+)\)/gi, "VARCHAR($1)");
  converted = converted.replace(/\bNVARCHAR2\s*\(([^)]+)\)/gi, "VARCHAR($1)");
  converted = converted.replace(/\bNUMBER\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/gi, "NUMERIC($1,$2)");
  converted = converted.replace(/\bNUMBER\s*\(\s*(\d+)\s*\)/gi, "NUMERIC($1)");
  converted = converted.replace(/\bNUMBER\b/gi, "NUMERIC");
  converted = converted.replace(/\bDATE\b/gi, "TIMESTAMP");
  converted = converted.replace(/\bCLOB\b/gi, "TEXT");
  converted = converted.replace(/\bBLOB\b/gi, "BYTEA");

  // Functions
  converted = converted.replace(/\bNVL\s*\(/gi, "COALESCE(");
  converted = converted.replace(/\bSYSDATE\b/gi, "CURRENT_DATE");
  converted = converted.replace(/\bSYSTIMESTAMP\b/gi, "CURRENT_TIMESTAMP");

  // Oracle string concatenation works in PostgreSQL, so keep ||
  // Convert DECODE placeholder
  converted = converted.replace(/\bDECODE\s*\(/gi, "/* DECODE needs CASE rewrite */ DECODE(");

  // TO_DATE and TO_CHAR mostly exist, but formats often need checking
  converted = converted.replace(/'YYYY-MM-DD HH24:MI:SS'/gi, "'YYYY-MM-DD HH24:MI:SS'");

  // Sequences
  converted = converted.replace(/(\w+)\.NEXTVAL/gi, "nextval('$1')");
  converted = converted.replace(/(\w+)\.CURRVAL/gi, "currval('$1')");

  // DUAL
  converted = converted.replace(/\s+FROM\s+DUAL\b/gi, "");

  // ROWNUM simple rewrite
  converted = converted.replace(/WHERE\s+ROWNUM\s*<=\s*(\d+)/gi, "LIMIT $1");
  converted = converted.replace(/\bROWNUM\s*<=\s*(\d+)/gi, "LIMIT $1");

  // Oracle outer join marker
  converted = converted.replace(/\(\+\)/g, "/* TODO: convert Oracle outer join to LEFT/RIGHT JOIN */");

  // CREATE TABLE cleanup
  converted = converted.replace(/\bENABLE\b/gi, "");
  converted = converted.replace(/\bDISABLE\b/gi, "");
  converted = converted.replace(/\bUSING INDEX\b/gi, "");
  converted = converted.replace(/\bTABLESPACE\s+\w+/gi, "");
  converted = converted.replace(/\bSTORAGE\s*\([^)]*\)/gi, "");

  // Auto-increment patterns
  converted = converted.replace(/\bGENERATED BY DEFAULT AS IDENTITY\b/gi, "GENERATED BY DEFAULT AS IDENTITY");
  converted = converted.replace(/\bGENERATED ALWAYS AS IDENTITY\b/gi, "GENERATED ALWAYS AS IDENTITY");

  // PL/SQL notes
  converted = converted.replace(/\bBEGIN\b/gi, "BEGIN");
  converted = converted.replace(/\bEND;\b/gi, "END;");

  // Add warning header
  converted =
`-- Converted from Oracle SQL to PostgreSQL.
-- Review manually before running, especially joins, DECODE, procedures, packages, triggers, and date formats.

${converted}`;

  document.getElementById("pgOutput").value = converted;
}

function copyOutput() {
  const output = document.getElementById("pgOutput");
  output.select();
  navigator.clipboard.writeText(output.value);
  alert("Converted SQL copied to clipboard!");
}

function clearFields() {
  document.getElementById("oracleInput").value = "";
  document.getElementById("pgOutput").value = "";
}
